ALTER TABLE vereadores ADD COLUMN IF NOT EXISTS partido TEXT;
ALTER TABLE vereadores ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE vereadores ADD COLUMN IF NOT EXISTS telefone TEXT;
ALTER TABLE vereadores ADD COLUMN IF NOT EXISTS instagram TEXT;